### ISSUE TITLE
Exporting Statutory Reports

### ISSUE THREAD

**Issue by PuravUdayDesai** [kevinam99/nodejs-tally-integration#2]
@kevinam99, I am trying to export the GST Reports **(Gateway Of Tally > Display > Statutory Reports > GST > GSTR-1 and GSTR-3B Reports)**, I tried but I am not able to find any XML Request for the respective, please help me by providing solution for the respective feature.

**Comment by kevinam99** [comment]
@PuravUdayDesai The customisable software is now available as a gig on [Fiverr](https://www.fiverr.com/s2/20eb7a4d8d)
Support me and my work by buying this project.
